services:
  # 🟢 BACKEND SERVICE (Node.js + Express)
  - type: web
    name: backend-service
    env: node
    rootDir: backened
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      # 🔐 Variables de entorno del backend
      - key: SUMSUB_BASE_URL
        value: https://api.sumsub.com
      - key: SUMSUB_APP_TOKEN
        sync: false
      - key: SUMSUB_SECRET_KEY
        sync: false
      - key: SUMSUB_LEVEL_NAME_US
        value: "Us citizen"
      - key: SUMSUB_LEVEL_NAME_OTHER
        value: id-and-liveness
      - key: RPC_URL
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: AUTHORIZE_CONTRACT_ADDRESS
        sync: false
      - key: PRESALE_CONTRACT_ADDRESS
        sync: false
      - key: CHAIN_ID
        sync: false
      - key: PORT
        sync: false
